/// 记录页面路径常量
export default abstract class PagePathConstants {
  // 网络请求示例
  static PAGE_HTTP_REQUEST: string = '/page/HttpRequestPage'
  // 消息通知示例
  static PAGE_EVENT_BUS: string = '/page/EventBusExample'
  // 自定义弹窗示例
  static PAGE_CUSTOM_DIALOG: string = '/page/CustomPageExample'
  // 路由回调示例
  static PAGE_ROUTER_CALLBACK: string = '/page/RouterCallbackExample'
  // Nav路由示例页面
  static PAGE_NAV_ROUTER_TEST: string = '/page/NavRouterTestPage'
}