/// 记录页面路径常量
export default abstract class PagePathConstants {
  // 网络请求示例
  static PAGE_HTTP_REQUEST: string = '/page/HttpRequestPage'
  // 消息通知示例
  static PAGE_EVENT_BUS: string = '/page/EventBusExample'
  // 自定义弹窗示例
  static PAGE_CUSTOM_DIALOG: string = '/page/CustomPageExample'
  // 路由回调示例
  static PAGE_ROUTER_CALLBACK: string = '/page/RouterCallbackExample'
  // Nav路由示例页面
  static PAGE_NAV_ROUTER_TEST: string = '/page/NavRouterTestPage'
  // 节流防抖示例
  static PAGE_THROTTLE_TEST: string = '/page/ThrottleExample'
  // 简易授权示例
  static PAGE_PERMISSION_TEST: string = '/page/PermissionExample'
  // 测试动态路由
  static DYNAMIC_ROUTER_TEST: string = '@ohos/feature_setting*./src/main/ets/TestDynamicNavPage'
  // UI动态节点示例
  static DYNAMIC_UI_NODE_TEST: string = '/page/BuilderNodeExample'
  // 适配折叠屏
  static FIX_FOLD_UI_EXAMPLE: string = '/page/FixFoldUiExample'
  // 组件工厂示例
  static COMPONENT_FACTORY_EXAMPLE: string = '/page/ComponentFactoryExample'
  // 组件动态属性示例
  static ATTRIBUTE_MODIFIER_EXAMPLE: string = '/page/AttributeModifierExample'
  // 云函数调用示例
  static CLOUD_FUNCTION_EXAMPLE: string = '/page/CloudFuncExample'
  // 云数据库使用示例
  static CLOUD_DATA_BASE_EXAMPLE: string = '/page/CloudDatabaseExample'
}